--- Tests for civic.ledger

local describe, it, expect = lust.describe, lust.it, lust.expect

local lg   = require("civic.ledger")
local civic = require("civic")

-- ─── Happy path ──────────────────────────────────────────────────────────────

describe("civic.ledger — happy path", function()
    it("new() returns an empty ledger", function()
        local book = lg.new()
        expect(book).to.exist()
        expect(book:size()).to.equal(0)
        expect(book:total()).to.equal(0)
        expect(book:credit_total()).to.equal(0)
    end)

    it("credit adds inflow to a slot", function()
        local book = lg.new()
        book:credit(1, 100)
        expect(book:balance(1)).to.equal(100)
        expect(book:total()).to.equal(100)
        expect(book:credit_total()).to.equal(100)
    end)

    it("transfer moves funds between slots", function()
        local book = lg.new()
        book:credit(1, 100)
        local ok = book:transfer(1, 2, 30)
        expect(ok).to.equal(true)
        expect(book:balance(1)).to.equal(70)
        expect(book:balance(2)).to.equal(30)
    end)

    it("transfer returns false on insufficient funds (default)", function()
        local book = lg.new()
        book:credit(1, 10)
        local ok = book:transfer(1, 2, 50)
        expect(ok).to.equal(false)
        expect(book:balance(1)).to.equal(10)
        expect(book:balance(2)).to.equal(0)
    end)

    it("allow_negative permits negative balance", function()
        local book = lg.new({ allow_negative = true })
        book:credit(1, 10)
        local ok = book:transfer(1, 2, 50)
        expect(ok).to.equal(true)
        expect(book:balance(1)).to.equal(-40)
        expect(book:balance(2)).to.equal(50)
    end)

    it("transactions records credit and transfer entries", function()
        local book = lg.new()
        book:credit(1, 100)
        book:transfer(1, 2, 30)
        local txs = book:transactions()
        expect(#txs).to.equal(2)
        expect(txs[1].kind).to.equal("credit")
        expect(txs[1].amount).to.equal(100)
        expect(txs[2].kind).to.equal("transfer")
        expect(txs[2].from).to.equal(1)
        expect(txs[2].to).to.equal(2)
    end)

    it("balance returns 0 for unknown slot", function()
        local book = lg.new()
        expect(book:balance(99)).to.equal(0)
    end)

    it("Ledger metatable is exposed", function()
        expect(lg.Ledger).to.exist()
        expect(lg.Ledger.__index).to.exist()
    end)
end)

-- ─── Reject ──────────────────────────────────────────────────────────────────

describe("civic.ledger — reject", function()
    it("credit rejects non-positive-integer slot", function()
        local book = lg.new()
        local ok, err = pcall(function() book:credit(0, 10) end)
        expect(ok).to.equal(false)
        expect(err:find("slot must be positive integer")).to.exist()
    end)

    it("credit rejects negative amount", function()
        local book = lg.new()
        local ok, err = pcall(function() book:credit(1, -5) end)
        expect(ok).to.equal(false)
        expect(err:find("amount must be non%-negative number")).to.exist()
    end)

    it("transfer rejects from = 0", function()
        local book = lg.new()
        local ok, err = pcall(function() book:transfer(0, 2, 10) end)
        expect(ok).to.equal(false)
        expect(err:find("from must be positive integer")).to.exist()
    end)

    it("transfer rejects to = 0", function()
        local book = lg.new()
        local ok, err = pcall(function() book:transfer(1, 0, 10) end)
        expect(ok).to.equal(false)
        expect(err:find("to must be positive integer")).to.exist()
    end)

    it("transfer rejects from == to (self-transfer)", function()
        local book = lg.new()
        local ok, err = pcall(function() book:transfer(1, 1, 10) end)
        expect(ok).to.equal(false)
        expect(err:find("from == to is meaningless")).to.exist()
    end)

    it("transfer rejects non-positive amount", function()
        local book = lg.new()
        local ok, err = pcall(function() book:transfer(1, 2, 0) end)
        expect(ok).to.equal(false)
        expect(err:find("amount must be positive number")).to.exist()
    end)

    it("transfer rejects negative amount", function()
        local book = lg.new()
        local ok, err = pcall(function() book:transfer(1, 2, -5) end)
        expect(ok).to.equal(false)
        expect(err:find("amount must be positive number")).to.exist()
    end)

    it("new rejects non-boolean allow_negative", function()
        local ok, err = pcall(function() lg.new({ allow_negative = "yes" }) end)
        expect(ok).to.equal(false)
        expect(err:find("opts.allow_negative must be boolean")).to.exist()
    end)
end)

-- ─── Invariant ───────────────────────────────────────────────────────────────

describe("civic.ledger — invariant", function()
    it("zero-sum: total == credit_total after credits and transfers", function()
        local book = lg.new()
        book:credit(1, 100)
        book:credit(2, 50)
        book:transfer(1, 2, 30)
        book:transfer(2, 1, 10)
        expect(book:total()).to.equal(book:credit_total())
        expect(book:total()).to.equal(150)
    end)

    it("zero-sum holds after rejected transfer", function()
        local book = lg.new()
        book:credit(1, 10)
        local ok = book:transfer(1, 2, 50)
        expect(ok).to.equal(false)
        expect(book:total()).to.equal(book:credit_total())
    end)

    it("zero-sum holds with allow_negative", function()
        local book = lg.new({ allow_negative = true })
        book:credit(1, 10)
        book:transfer(1, 2, 50)
        expect(book:total()).to.equal(book:credit_total())
        expect(book:total()).to.equal(10)
    end)

    it("transactions is append-only", function()
        local book = lg.new()
        book:credit(1, 10)
        book:transfer(1, 2, 5)
        book:credit(2, 20)
        expect(book:size()).to.equal(3)
    end)

    it("transactions returns defensive copy", function()
        local book = lg.new()
        book:credit(1, 10)
        local t1 = book:transactions()
        t1[1].amount = 999
        local t2 = book:transactions()
        expect(t2[1].amount).to.equal(10)
    end)

    it("new() produces independent instances", function()
        local b1 = lg.new()
        local b2 = lg.new()
        b1:credit(1, 100)
        expect(b1:total()).to.equal(100)
        expect(b2:total()).to.equal(0)
    end)

    it("civic.ledger is wired from civic/init.lua", function()
        expect(civic.ledger).to.exist()
        expect(civic.ledger.new).to.exist()
    end)

    it("civic.shape.ledger_tx is exposed", function()
        expect(civic.shape.ledger_tx).to.exist()
        expect(type(civic.shape.ledger_tx)).to.equal("table")
    end)
end)
