--- Tests for civic.lineage

local describe, it, expect = lust.describe, lust.it, lust.expect

local lin  = require("civic.lineage")
local civic = require("civic")

-- ─── Happy path ──────────────────────────────────────────────────────────────

describe("civic.lineage — happy path", function()
    it("new() returns an empty lineage graph", function()
        local g = lin.new()
        expect(g).to.exist()
        expect(g:size()).to.equal(0)
    end)

    it("set_mutation_op registers a function", function()
        local g = lin.new()
        g:set_mutation_op(function(p) return p end)
        expect(g:size()).to.equal(0)
    end)

    it("beget creates child payload via mutation_op and records edge", function()
        local g = lin.new()
        g:set_mutation_op(function(p) return { fitness = p.fitness * 0.9 } end)
        local child = g:beget(1, 2, 1, { fitness = 10 })
        expect(child.fitness).to.equal(9)
        expect(g:size()).to.equal(1)
    end)

    it("parent returns the parent slot", function()
        local g = lin.new()
        g:set_mutation_op(function(p) return { v = p.v } end)
        g:beget(5, 10, 0, { v = 1 })
        expect(g:parent(10)).to.equal(5)
    end)

    it("children returns child list", function()
        local g = lin.new()
        g:set_mutation_op(function(p) return { v = p.v } end)
        g:beget(1, 2, 0, { v = 1 })
        g:beget(1, 3, 0, { v = 1 })
        local kids = g:children(1)
        expect(#kids).to.equal(2)
        expect(kids[1]).to.equal(2)
        expect(kids[2]).to.equal(3)
    end)

    it("children returns empty list for unknown parent", function()
        local g = lin.new()
        expect(#g:children(99)).to.equal(0)
    end)

    it("generation returns the gen number", function()
        local g = lin.new()
        g:set_mutation_op(function(p) return { v = p.v } end)
        g:beget(1, 2, 5, { v = 1 })
        expect(g:generation(2)).to.equal(5)
    end)

    it("generation returns 0 for unknown slot", function()
        local g = lin.new()
        expect(g:generation(99)).to.equal(0)
    end)

    it("edges returns full history", function()
        local g = lin.new()
        g:set_mutation_op(function(p) return { v = p.v } end)
        g:beget(1, 2, 0, { v = 1 })
        g:beget(2, 3, 1, { v = 1 })
        local e = g:edges()
        expect(#e).to.equal(2)
        expect(e[1].parent).to.equal(1)
        expect(e[2].child).to.equal(3)
    end)

    it("Lineage metatable is exposed", function()
        expect(lin.Lineage).to.exist()
        expect(lin.Lineage.__index).to.exist()
    end)
end)

-- ─── Reject ──────────────────────────────────────────────────────────────────

describe("civic.lineage — reject", function()
    it("beget raises when mutation_op not set", function()
        local g = lin.new()
        local ok, err = pcall(function() g:beget(1, 2, 0, { v = 1 }) end)
        expect(ok).to.equal(false)
        expect(err:find("mutation_op not set")).to.exist()
    end)

    it("set_mutation_op rejects non-function", function()
        local g = lin.new()
        local ok, err = pcall(function() g:set_mutation_op("bad") end)
        expect(ok).to.equal(false)
        expect(err:find("fn must be function")).to.exist()
    end)

    it("beget rejects parent_slot = 0", function()
        local g = lin.new()
        g:set_mutation_op(function(p) return p end)
        local ok, err = pcall(function() g:beget(0, 2, 0, { v = 1 }) end)
        expect(ok).to.equal(false)
        expect(err:find("parent_slot must be positive integer")).to.exist()
    end)

    it("beget rejects non-integer child_slot", function()
        local g = lin.new()
        g:set_mutation_op(function(p) return p end)
        local ok, err = pcall(function() g:beget(1, 2.5, 0, { v = 1 }) end)
        expect(ok).to.equal(false)
        expect(err:find("child_slot must be positive integer")).to.exist()
    end)

    it("beget rejects negative gen", function()
        local g = lin.new()
        g:set_mutation_op(function(p) return p end)
        local ok, err = pcall(function() g:beget(1, 2, -1, { v = 1 }) end)
        expect(ok).to.equal(false)
        expect(err:find("gen must be non%-negative integer")).to.exist()
    end)

    it("beget rejects non-table parent_payload", function()
        local g = lin.new()
        g:set_mutation_op(function(p) return p end)
        local ok, err = pcall(function() g:beget(1, 2, 0, "bad") end)
        expect(ok).to.equal(false)
        expect(err:find("parent_payload must be table")).to.exist()
    end)

    it("beget rejects mutation_op returning non-table", function()
        local g = lin.new()
        g:set_mutation_op(function(p) return 42 end)
        local ok, err = pcall(function() g:beget(1, 2, 0, { v = 1 }) end)
        expect(ok).to.equal(false)
        expect(err:find("mutation_op must return table")).to.exist()
    end)
end)

-- ─── Invariant ───────────────────────────────────────────────────────────────

describe("civic.lineage — invariant", function()
    it("edges is append-only (grows with each beget)", function()
        local g = lin.new()
        g:set_mutation_op(function(p) return { v = p.v } end)
        g:beget(1, 2, 0, { v = 1 })
        g:beget(2, 3, 1, { v = 1 })
        g:beget(3, 4, 2, { v = 1 })
        expect(g:size()).to.equal(3)
    end)

    it("slot reuse overwrites indexed accessors but preserves edge history", function()
        local g = lin.new()
        g:set_mutation_op(function(p) return { v = p.v + 1 } end)
        g:beget(1, 2, 0, { v = 0 })
        g:beget(3, 2, 1, { v = 10 })
        expect(g:parent(2)).to.equal(3)
        expect(g:generation(2)).to.equal(1)
        local e = g:edges()
        expect(#e).to.equal(2)
        expect(e[1].parent).to.equal(1)
        expect(e[2].parent).to.equal(3)
    end)

    it("edges returns defensive copy", function()
        local g = lin.new()
        g:set_mutation_op(function(p) return { v = p.v } end)
        g:beget(1, 2, 0, { v = 1 })
        local e1 = g:edges()
        e1[1].parent = 999
        local e2 = g:edges()
        expect(e2[1].parent).to.equal(1)
    end)

    it("children returns defensive copy", function()
        local g = lin.new()
        g:set_mutation_op(function(p) return { v = p.v } end)
        g:beget(1, 2, 0, { v = 1 })
        local kids1 = g:children(1)
        kids1[1] = 999
        local kids2 = g:children(1)
        expect(kids2[1]).to.equal(2)
    end)

    it("new() produces independent instances", function()
        local g1 = lin.new()
        local g2 = lin.new()
        g1:set_mutation_op(function(p) return p end)
        g1:beget(1, 2, 0, { v = 1 })
        expect(g1:size()).to.equal(1)
        expect(g2:size()).to.equal(0)
    end)

    it("civic.lineage is wired from civic/init.lua", function()
        expect(civic.lineage).to.exist()
        expect(civic.lineage.new).to.exist()
    end)

    it("civic.shape.lineage_edge is exposed", function()
        expect(civic.shape.lineage_edge).to.exist()
        expect(type(civic.shape.lineage_edge)).to.equal("table")
    end)
end)
