--- Tests for civic.scalar_pool

local describe, it, expect = lust.describe, lust.it, lust.expect

local sp   = require("civic.scalar_pool")
local civic = require("civic")

-- ─── Happy path ──────────────────────────────────────────────────────────────

describe("civic.scalar_pool — happy path", function()
    it("new() returns an empty pool", function()
        local pool = sp.new()
        expect(pool).to.exist()
        expect(#pool:slots()).to.equal(0)
    end)

    it("credit adds to a (slot, source) bucket", function()
        local pool = sp.new()
        pool:credit(1, "tournament", 5)
        expect(pool:by_source(1, "tournament")).to.equal(5)
    end)

    it("credit accumulates across multiple calls", function()
        local pool = sp.new()
        pool:credit(1, "peer", 3)
        pool:credit(1, "peer", 7)
        expect(pool:by_source(1, "peer")).to.equal(10)
    end)

    it("debit subtracts from a bucket", function()
        local pool = sp.new()
        pool:credit(1, "trial", 10)
        pool:debit(1, "trial", 3)
        expect(pool:by_source(1, "trial")).to.equal(7)
    end)

    it("total sums across all sources for a slot", function()
        local pool = sp.new()
        pool:credit(1, "a", 5)
        pool:credit(1, "b", 3)
        expect(pool:total(1)).to.equal(8)
    end)

    it("total returns 0 for unknown slot", function()
        local pool = sp.new()
        expect(pool:total(99)).to.equal(0)
    end)

    it("by_source returns 0 for unknown bucket", function()
        local pool = sp.new()
        expect(pool:by_source(1, "x")).to.equal(0)
    end)

    it("reset drops a slot entirely", function()
        local pool = sp.new()
        pool:credit(1, "a", 10)
        pool:reset(1)
        expect(pool:total(1)).to.equal(0)
        expect(#pool:slots()).to.equal(0)
    end)

    it("apply_decay multiplies all buckets by rate", function()
        local pool = sp.new()
        pool:credit(1, "a", 10)
        pool:credit(2, "b", 20)
        pool:apply_decay(0.5)
        expect(pool:by_source(1, "a")).to.equal(5)
        expect(pool:by_source(2, "b")).to.equal(10)
    end)

    it("slots returns sorted list of active indices", function()
        local pool = sp.new()
        pool:credit(3, "x", 1)
        pool:credit(1, "x", 1)
        pool:credit(5, "x", 1)
        local s = pool:slots()
        expect(#s).to.equal(3)
        expect(s[1]).to.equal(1)
        expect(s[2]).to.equal(3)
        expect(s[3]).to.equal(5)
    end)

    it("Pool metatable is exposed", function()
        expect(sp.Pool).to.exist()
        expect(sp.Pool.__index).to.exist()
    end)
end)

-- ─── Reject ──────────────────────────────────────────────────────────────────

describe("civic.scalar_pool — reject", function()
    it("credit rejects slot = 0", function()
        local pool = sp.new()
        local ok, err = pcall(function() pool:credit(0, "a", 1) end)
        expect(ok).to.equal(false)
        expect(err:find("slot must be positive integer")).to.exist()
    end)

    it("credit rejects empty source", function()
        local pool = sp.new()
        local ok, err = pcall(function() pool:credit(1, "", 1) end)
        expect(ok).to.equal(false)
        expect(err:find("source must be non%-empty string")).to.exist()
    end)

    it("credit rejects non-string source", function()
        local pool = sp.new()
        local ok, err = pcall(function() pool:credit(1, 42, 1) end)
        expect(ok).to.equal(false)
        expect(err:find("source must be non%-empty string")).to.exist()
    end)

    it("credit rejects non-number amount", function()
        local pool = sp.new()
        local ok, err = pcall(function() pool:credit(1, "a", "bad") end)
        expect(ok).to.equal(false)
        expect(err:find("amount must be number")).to.exist()
    end)

    it("debit rejects non-positive-integer slot", function()
        local pool = sp.new()
        local ok, err = pcall(function() pool:debit(-1, "a", 1) end)
        expect(ok).to.equal(false)
        expect(err:find("slot must be positive integer")).to.exist()
    end)

    it("reset rejects non-positive-integer slot", function()
        local pool = sp.new()
        local ok, err = pcall(function() pool:reset(0) end)
        expect(ok).to.equal(false)
        expect(err:find("slot must be positive integer")).to.exist()
    end)

    it("apply_decay rejects rate > 1", function()
        local pool = sp.new()
        local ok, err = pcall(function() pool:apply_decay(1.5) end)
        expect(ok).to.equal(false)
        expect(err:find("rate must be number in %[0, 1%]")).to.exist()
    end)

    it("apply_decay rejects negative rate", function()
        local pool = sp.new()
        local ok, err = pcall(function() pool:apply_decay(-0.1) end)
        expect(ok).to.equal(false)
        expect(err:find("rate must be number in %[0, 1%]")).to.exist()
    end)

    it("apply_decay rejects non-number rate", function()
        local pool = sp.new()
        local ok, err = pcall(function() pool:apply_decay("half") end)
        expect(ok).to.equal(false)
        expect(err:find("rate must be number in %[0, 1%]")).to.exist()
    end)
end)

-- ─── Invariant ───────────────────────────────────────────────────────────────

describe("civic.scalar_pool — invariant", function()
    it("decay preserves relative proportions between sources", function()
        local pool = sp.new()
        pool:credit(1, "a", 10)
        pool:credit(1, "b", 20)
        pool:apply_decay(0.5)
        local a = pool:by_source(1, "a")
        local b = pool:by_source(1, "b")
        expect(b / a).to.equal(2)
    end)

    it("decay with rate=0 zeros all buckets", function()
        local pool = sp.new()
        pool:credit(1, "a", 100)
        pool:apply_decay(0)
        expect(pool:by_source(1, "a")).to.equal(0)
    end)

    it("decay with rate=1 is identity", function()
        local pool = sp.new()
        pool:credit(1, "a", 42)
        pool:apply_decay(1)
        expect(pool:by_source(1, "a")).to.equal(42)
    end)

    it("credit with negative amount reduces bucket", function()
        local pool = sp.new()
        pool:credit(1, "a", 10)
        pool:credit(1, "a", -3)
        expect(pool:by_source(1, "a")).to.equal(7)
    end)

    it("debit is symmetric with credit of negative", function()
        local p1 = sp.new()
        p1:credit(1, "a", 10)
        p1:credit(1, "a", -3)

        local p2 = sp.new()
        p2:credit(1, "a", 10)
        p2:debit(1, "a", 3)

        expect(p1:by_source(1, "a")).to.equal(p2:by_source(1, "a"))
    end)

    it("reset followed by credit starts fresh", function()
        local pool = sp.new()
        pool:credit(1, "a", 100)
        pool:reset(1)
        pool:credit(1, "a", 5)
        expect(pool:by_source(1, "a")).to.equal(5)
        expect(pool:total(1)).to.equal(5)
    end)

    it("new() produces independent instances", function()
        local p1 = sp.new()
        local p2 = sp.new()
        p1:credit(1, "x", 10)
        expect(p1:total(1)).to.equal(10)
        expect(p2:total(1)).to.equal(0)
    end)

    it("civic.scalar_pool is wired from civic/init.lua", function()
        expect(civic.scalar_pool).to.exist()
        expect(civic.scalar_pool.new).to.exist()
    end)

    it("civic.shape.scalar_bucket is exposed", function()
        expect(civic.shape.scalar_bucket).to.exist()
        expect(type(civic.shape.scalar_bucket)).to.equal("table")
    end)
end)
